import ReceivingIssueFields from '../../components/ReceivingIssueFields';
import {useEffect,useState} from "react";
import client from "../../api/client";
import DataTable from "../../components/DataTable";
import DocumentAttachments from "../../components/DocumentAttachments";
import Modal from "../../components/Modal";
import {useAuth} from "../../contexts/AuthContext";
import {isUsableStorageLocation,locationLabel} from "../../utils/locations";
import useAutoRefresh from "../../hooks/useAutoRefresh";

export default function ReceivingControlPage(){
  const {user}=useAuth();const [employees,setEmployees]=useState([]);const [rows,setRows]=useState([]);const [locations,setLocations]=useState([]);const [active,setActive]=useState(null);const [recommendation,setRecommendation]=useState(null);const [form,setForm]=useState({inspected_quantity:"",passed_quantity:"",failed_quantity:"",remarks:"",selected_location_id:"",override_reason:""});const [error,setError]=useState("");
  const canInspect=["SupplyChainManager","WarehouseManager","WarehouseSupervisor"].includes(user?.role);
  const load=()=>client.get("/warehouse/receiving-queue").then(r=>setRows(r.data)).catch(e=>setError(e.response?.data?.error||"Unable to load receiving control queue"));
  useAutoRefresh(load);
  useEffect(()=>{load();client.get("/masters/employee-directory").then(r=>setEmployees(r.data)).catch(()=>{});client.get("/masters/locations").then(r=>setLocations(r.data.filter(l=>isUsableStorageLocation(l)&&l.is_terminal_storage)));},[]);
  async function inspect(){try{await client.post("/warehouse/inspections",{hold_id:active.id,inspected_quantity:Number(form.inspected_quantity),passed_quantity:Number(form.passed_quantity),failed_quantity:Number(form.failed_quantity),remarks:form.remarks,damaged_quantity:form.damaged_quantity,issue_reason:form.issue_reason,inspector_name:form.inspector_name,inspector_department:form.inspector_department,inspector_designation:form.inspector_designation});setActive(null);setError("");load();}catch(e){setError(e.response?.data?.error||"Inspection could not be recorded");}}
  async function recommend(row){try{const {data}=await client.post("/masters/putaway/recommend",{item_id:row.item_id,warehouse_id:row.warehouse_id,quantity:row.quantity,inventory_status:"AVAILABLE",source_table:"inventory_quarantine",source_id:row.id});setActive(row);setRecommendation(data);setForm({...form,selected_location_id:data.location.id,override_reason:""});setError("");}catch(e){setError(e.response?.data?.error||"No compatible storage location is currently available for this item.");}}
  async function confirm(){try{await client.put(`/masters/putaway/${recommendation.recommendation_id}/confirm`,{selected_location_id:Number(form.selected_location_id),override_reason:form.override_reason});setActive(null);setRecommendation(null);setError("");load();}catch(e){setError(e.response?.data?.error||"Put-away could not be confirmed");}}
  const columns=[{key:"grn_number",label:"GRN"},{key:"item_code",label:"Item"},{key:"description",label:"Description"},{key:"quantity",label:"Quantity"},{key:"uom",label:"UOM"},{key:"batch",label:"Batch"},{key:"expiry_date",label:"Expiry"},{key:"inventory_status",label:"Status"},{key:"current_location_code",label:"Staging Location"}];
  return <div><div className="mb-4"><h1 className="text-xl font-semibold">Inspection & Put-Away</h1><p className="text-sm text-slate-500">Restricted receiving stock becomes available only after inspection release where required and confirmed physical put-away.</p></div>{error&&<div data-error-message="true" role="alert" className="mb-3 rounded bg-rose-50 p-3 text-sm text-rose-700">{error}</div>}<div className="card"><DataTable rows={rows} columns={columns} actionLabel="Process" actions={row=>row.inventory_status==="INSPECTION_PENDING"?<div className="space-y-2"><button className="btn-secondary text-xs" disabled={!canInspect} title={!canInspect?"Inspection must be recorded by SCM, Warehouse Manager or Warehouse Supervisor for this warehouse.":undefined} onClick={()=>{setError("");setActive(row);setRecommendation(null);const inspector=employees.find(e=>Number(e.id)===Number(user?.employee_id));setForm({...form,inspector_name:inspector?.name||user?.full_name||"",inspector_department:inspector?.department_name||"",inspector_designation:inspector?.position||"",inspected_quantity:row.quantity-row.inspected_quantity,passed_quantity:row.quantity-row.inspected_quantity,failed_quantity:0,damaged_quantity:0,issue_reason:"",remarks:""});}}>Record Inspection</button>{!canInspect&&<p className="text-sm text-slate-600" role="note">Ask the SCM, Warehouse Manager or Warehouse Supervisor assigned to this warehouse to record the inspection. Storekeepers can complete put-away after inspection release.</p>}</div>:<button className="btn-primary text-xs" onClick={()=>recommend(row)}>Recommend Put-Away</button>}/></div>
  {active&&!recommendation&&<Modal title={`Inspection — ${active.item_code}`} onClose={()=>setActive(null)}><div className="space-y-3"><p className="text-sm">Accepted: {active.quantity} {active.uom} · Previously inspected: {active.inspected_quantity||0}</p>{[["inspector_name","Inspection Person Name"],["inspector_department","Department"],["inspector_designation","Designation"]].map(([key,label])=><label key={key} className="block text-sm font-medium">{label}<input data-field={key} className="input mt-1" value={form[key]||""} onChange={e=>setForm({...form,[key]:e.target.value})}/></label>)}{[["inspected_quantity","Inspected"],["passed_quantity","Passed"],["failed_quantity","Failed"]].map(([key,label])=><label key={key} className="block text-sm font-medium">{label}<input data-field={key} className="input mt-1" type="number" min="0" value={form[key]} onChange={e=>setForm({...form,[key]:e.target.value})}/></label>)}<ReceivingIssueFields line={form} inspection onChange={(key,value)=>setForm({...form,[key]:value})}/>{active.grn_id&&<section className="space-y-2"><h2 className="font-medium">Approval Document (Optional)</h2><p className="text-sm text-slate-500">Upload supporting approval evidence to this GRN if available. A document is not required to record the inspection.</p><DocumentAttachments type="GRN" documentId={active.grn_id}/></section>}{error&&<div data-error-message role="alert" className="rounded bg-rose-50 p-3 text-sm text-rose-700">{error}</div>}<button className="btn-primary" onClick={inspect}>Record Controlled Decision</button></div></Modal>}
  {active&&recommendation&&<Modal title={`Put-Away — ${active.item_code}`} onClose={()=>{setActive(null);setRecommendation(null);}}><div className="space-y-3"><div className="rounded bg-emerald-50 p-3 text-sm"><strong>Recommended:</strong> {locationLabel(recommendation.location)}<br/>{recommendation.reason}</div><label className="block text-sm font-medium">Confirmed Location<select data-field={"selected_location_id"} className="input mt-1" value={form.selected_location_id} onChange={e=>setForm({...form,selected_location_id:e.target.value})}>{(recommendation.compatible_locations||locations.filter(l=>Number(l.warehouse_id)===Number(active.warehouse_id))).map(l=><option key={l.id} value={l.id}>{locationLabel(l)}</option>)}</select></label>{Number(form.selected_location_id)!==Number(recommendation.location.id)&&<label className="block text-sm font-medium">Override Reason<textarea data-field={"override_reason"} className="input mt-1" value={form.override_reason} onChange={e=>setForm({...form,override_reason:e.target.value})}/></label>}<button className="btn-primary" onClick={confirm}>Confirm Put-Away & Make Available</button></div></Modal>}</div>;
}
