import { useEffect, useMemo, useState } from "react";
import client from "../../api/client";
import DataTable from "../../components/DataTable";
import Modal from "../../components/Modal";
import { useAuth } from "../../contexts/AuthContext";
import useAutoRefresh from "../../hooks/useAutoRefresh";

const parentTypes={Zone:[],Aisle:["Zone"],Rack:["Zone","Aisle"],Shelf:["Rack"],Bin:["Zone","Aisle","Rack","Shelf"],Bay:["Zone"],"Yard Slot":["Zone"],"Ground Stack":["Zone"],"Open Area":["Zone"],Staging:["Zone"]};
const structureLabels={AISLE_RACK_SHELF_BIN:"Aisle → Rack → Shelf → Bin",RACK_SHELF_BIN:"Rack → Shelf → Bin",RACK:"Rack Only",BAY:"Storage Bays",YARD_SLOT:"Yard Slots",GROUND_STACK:"Ground Stacks",BIN_ONLY:"Bins Only",OPEN_AREA:"Open Storage Area",STAGING:"Staging Area",QUARANTINE_AREA:"Quarantine Area",REPAIR_AREA:"Repair Area"};
const structures=Object.keys(structureLabels);
const DAY_NAMES=["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"];
const blankWarehouse={warehouse_code:"",name:"",site_type:"Factory",site_name:"",address:"",country_code:"",city_id:"",postal_code:"",region_province:"",time_zone:"Asia/Riyadh",operation_24h_yn:0,shifts_enabled_yn:1,operating_days:[0,1,2,3,4,5,6],operating_start_time:"03:00",operating_end_time:"03:00"};

export default function WarehousesPage(){
  const {user}=useAuth(),canDeactivate=user?.role==="SupplyChainManager";
  const [warehouses,setWarehouses]=useState([]),[locations,setLocations]=useState([]),[readiness,setReadiness]=useState(null),[reportDetail,setReportDetail]=useState(null),[shiftPreview,setShiftPreview]=useState(null),[deactivationReason,setDeactivationReason]=useState(""),[showWh,setShowWh]=useState(false),[showLoc,setShowLoc]=useState(false),[warehouseForm,setWarehouseForm]=useState(blankWarehouse),[locForm,setLocForm]=useState({type:"Zone",label:"",structure_type:"RACK_SHELF_BIN",storage_classification:"GENERAL",environment:"INDOOR",active_yn:1}),[error,setError]=useState(""),[reference,setReference]=useState({countries:[],cities:[]}),[timeZones,setTimeZones]=useState([]);
  const [hierarchyQuery,setHierarchyQuery]=useState("");
  const load=()=>Promise.all([client.get("/masters/warehouses"),client.get("/masters/locations")]).then(([w,l])=>{setWarehouses(w.data);setLocations(l.data);setError("");}).catch(e=>setError(e.response?.data?.error||"Unable to load warehouses and storage locations"));
  useAutoRefresh(load);
  useEffect(()=>{load();client.get("/workforce/reference").then(r=>setReference(r.data)).catch(()=>undefined);client.get("/masters/time-zones").then(r=>setTimeZones(r.data)).catch(()=>undefined);},[]);
  const parents=useMemo(()=>locations.filter(l=>Number(l.warehouse_id)===Number(locForm.warehouse_id)&&parentTypes[locForm.type]?.includes(l.type)),[locations,locForm]);
  async function saveWarehouse(){try{if(warehouseForm.id){const changed=warehouseForm.operating_start_time!==warehouseForm.original_operating_start_time||warehouseForm.operating_end_time!==warehouseForm.original_operating_end_time;if(changed){const preview=await client.post(`/masters/warehouses/${warehouseForm.id}/shift-design-preview`,warehouseForm);setShiftPreview(preview.data);return;}await client.put(`/masters/warehouses/${warehouseForm.id}`,warehouseForm);}else await client.post("/masters/warehouses",warehouseForm);setShowWh(false);setWarehouseForm(blankWarehouse);setError("");await load();}catch(e){setError(e.response?.data?.error||"Unable to save warehouse");}}
  async function confirmShiftDesign(){try{await client.put(`/masters/warehouses/${warehouseForm.id}`,{...warehouseForm,confirm_shift_design:true});setShiftPreview(null);setShowWh(false);setWarehouseForm(blankWarehouse);setError("");await load();}catch(e){setError(e.response?.data?.error||"Unable to confirm the automatic shift design");}}
  async function saveLocation(){try{if(locForm.id){await client.put(`/masters/locations/${locForm.id}`,locForm);if(Number(locForm.generation_count)>0)await client.post(`/masters/locations/${locForm.id}/generate`,{count:Number(locForm.generation_count)});}else{const created=await client.post("/masters/locations",locForm);if(Number(locForm.generation_count)>0&&locForm.structure_type&&!['OPEN_AREA','QUARANTINE_AREA','REPAIR_AREA'].includes(locForm.structure_type))await client.post(`/masters/locations/${created.data.id}/generate`,{count:Number(locForm.generation_count)});}setShowLoc(false);setLocForm({type:"Zone",label:""});setError("");await load();}catch(e){setError(e.response?.data?.error||"Unable to save location");}}
  async function quickSetup(){try{await client.post(`/masters/locations/${locForm.id}/quick-setup`,locForm.quick||{});setShowLoc(false);setError("");await load();}catch(e){setError(e.response?.data?.error||"Quick Setup failed");}}
  async function deleteLocation(){if(!window.confirm(`Permanently delete ${locForm.type} ${locForm.code} and every empty child location? This cannot be undone.`))return;try{await client.delete(`/masters/locations/${locForm.id}/permanent`);setShowLoc(false);setError("");await load();}catch(e){setError(e.response?.data?.error||"Location cannot be deleted because it contains data or operational history");}}
  async function inspectDeactivation(row){try{const r=await client.get(`/masters/warehouses/${row.id}/deactivation-readiness`);setReadiness(r.data);setDeactivationReason("");setError("");}catch(e){setError(e.response?.data?.error||"Unable to inspect warehouse deactivation readiness");}}
  async function deactivateWarehouse(){try{const r=await client.post(`/masters/warehouses/${readiness.warehouse.id}/deactivate`,{reason:deactivationReason});setReadiness(null);setDeactivationReason("");setError("");await load();const detail=await client.get(`/masters/warehouses/deactivation-reports/${r.data.report_id}`);setReportDetail(detail.data);}catch(e){setError(e.response?.data?.error||"Warehouse deactivation failed");}}
  const field=(label,key,type="text")=><label className="block text-sm font-medium">{label}<input data-field={key} type={type} className="input mt-1" value={warehouseForm[key]??""} onChange={e=>setWarehouseForm({...warehouseForm,[key]:e.target.value})}/></label>;
  const hierarchyMatches=node=>{const needle=hierarchyQuery.trim().toLowerCase();if(!needle)return true;const own=[node.code,node.label,node.type,node.storage_classification,node.environment,node.structure_type,node.hierarchy_path].some(value=>String(value||"").toLowerCase().includes(needle));return own||locations.some(child=>Number(child.parent_id)===Number(node.id)&&hierarchyMatches(child));};
  const renderNode=(node,depth=0)=>{const children=locations.filter(x=>Number(x.parent_id)===Number(node.id)&&hierarchyMatches(x));const summary=<div className="flex min-w-0 flex-1 items-center gap-2"><span className="shrink-0 font-mono text-xs font-semibold text-blue-800">{node.code}</span><span className="truncate text-sm">{node.label||node.type}</span><span className="shrink-0 rounded bg-slate-100 px-1.5 text-[10px]">{node.type}</span>{node.is_terminal_storage&&<span className="shrink-0 rounded bg-emerald-50 px-1.5 text-[10px] text-emerald-700">Final storage</span>}</div>;const manage=<button type="button" className="shrink-0 text-xs font-semibold text-blue-700" onClick={event=>{event.preventDefault();event.stopPropagation();setError("");setLocForm({...node,generation_count:""});setShowLoc(true);}}>Manage</button>;return children.length?<details open={hierarchyQuery?true:undefined} key={node.id} className="mt-1 rounded-md border border-slate-100 bg-white" style={{marginLeft:depth*12}}><summary className="flex cursor-pointer list-none items-center gap-2 px-2 py-1.5"><span className="text-[10px] text-slate-400">▶</span>{summary}{manage}</summary><div className="border-t border-slate-100 bg-slate-50/50 py-1">{children.map(child=>renderNode(child,depth+1))}</div></details>:<div key={node.id} className="mt-1 flex items-center gap-2 rounded-md border border-slate-100 bg-white px-2 py-1.5" style={{marginLeft:depth*12}}>{summary}{manage}</div>};
  return <div>
    <div className="mb-4"><h1 className="text-xl font-semibold text-slate-900">Warehouse Sites & Storage Locations</h1><p className="text-sm text-slate-500">Configure warehouse sites and their physical storage hierarchy.</p></div>
    {error&&!showWh&&!showLoc&&<div data-error-message="true" role="alert" className="mb-4 rounded-lg border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-700">{error}</div>}
    <div className="space-y-6">
      <div className="card p-4"><div className="mb-3 flex justify-between"><h2 className="font-medium">Warehouse Sites</h2><button className="btn-secondary text-xs" onClick={()=>{setError("");setWarehouseForm(blankWarehouse);setShowWh(true);}}>+ Add Warehouse</button></div>
        <DataTable rows={warehouses} columns={[{key:"warehouse_code",label:"Code"},{key:"name",label:"Warehouse"},{key:"time_zone",label:"Time Zone"},{key:"operating_start_time",label:"Opens"},{key:"operating_end_time",label:"Closes"},{key:"site_type",label:"Site Type"},{key:"city",label:"City"}]} actions={row=><div className="flex gap-2"><button className="btn-secondary text-xs" onClick={()=>{setError("");setWarehouseForm({...row,operating_days:row.operating_days||[],original_operating_start_time:row.operating_start_time,original_operating_end_time:row.operating_end_time});setShowWh(true);}}>Edit Warehouse</button>{canDeactivate&&<button className="rounded-lg border border-rose-200 px-2 py-1 text-xs font-medium text-rose-700 hover:bg-rose-50" onClick={()=>inspectDeactivation(row)}>Deactivate</button>}</div>}/>
      </div>
      <div className="card p-4"><div className="mb-3 flex justify-between"><div><h2 className="font-medium">Warehouse Storage Hierarchy</h2><p className="text-xs text-slate-500">Create Zones first, then manage each Rack or Shelf to generate its next physical level.</p></div><button className="btn-secondary text-xs" onClick={()=>{setError("");setLocForm({type:"Zone",label:"",structure_type:"RACK_SHELF_BIN",storage_classification:"GENERAL",environment:"INDOOR",active_yn:1});setShowLoc(true);}}>+ Create Zone</button></div>
        <input data-field={"hierarchyQuery"} type="search" className="input mb-2 w-full max-w-sm" placeholder="Search hierarchy by code, location, level, or classification..." value={hierarchyQuery} onChange={event=>setHierarchyQuery(event.target.value)}/>
        <div className="mb-4 space-y-2">{warehouses.filter(w=>!hierarchyQuery||`${w.warehouse_code} ${w.name}`.toLowerCase().includes(hierarchyQuery.toLowerCase())||locations.some(x=>Number(x.warehouse_id)===Number(w.id)&&x.type==="Zone"&&hierarchyMatches(x))).map(w=><details open={hierarchyQuery?true:undefined} key={w.id} className="rounded-lg border border-slate-200 bg-slate-50"><summary className="flex cursor-pointer items-center justify-between px-3 py-2 font-semibold text-slate-900"><span>{w.warehouse_code||`WH${w.id}`} — {w.name||"Unnamed warehouse"}</span><span className="text-xs font-normal text-slate-500">{locations.filter(x=>Number(x.warehouse_id)===Number(w.id)).length} locations · Expand hierarchy</span></summary><div className="border-t border-slate-200 p-2">{locations.filter(x=>Number(x.warehouse_id)===Number(w.id)&&x.type==="Zone"&&hierarchyMatches(x)).map(zone=>renderNode(zone))}</div></details>)}</div>
        <details className="rounded-lg border border-slate-200 bg-white"><summary className="cursor-pointer px-3 py-2"><span className="font-medium">All Physical Locations</span><span className="ml-2 text-xs text-slate-500">{locations.length} records · Expand compact register</span></summary><div className="border-t border-slate-200"><p className="px-3 pt-3 text-xs text-slate-500">Search remains available below. Use View Details for the complete location record and Manage for editing.</p><DataTable actionLabel="View Details" rows={locations.map(x=>({...x,master_state:Number(x.active_yn)===0?"Inactive":"Active",operational_availability:x.status,structure_name:structureLabels[x.structure_type]||x.structure_type,capacity_display:x.capacity_quantity?`${x.capacity_quantity} ${x.capacity_uom||""}`.trim():"—"}))} columns={[{key:"code",label:"Code"},{key:"label",label:"Location"},{key:"type",label:"Level"},{key:"warehouse_name",label:"Warehouse"},{key:"operational_availability",label:"Availability"},{key:"master_state",label:"State"},{key:"capacity_display",label:"Capacity"}]} actions={row=><button className="btn-secondary text-xs" onClick={()=>{setError("");setLocForm({...row,generation_count:""});setShowLoc(true);}}>Manage {row.type}</button>}/></div></details>
      </div>
    </div>
    {showWh&&<Modal title={warehouseForm.id?"Edit Warehouse Site":"New Warehouse Site"} onClose={()=>setShowWh(false)}>
      <div className="compact-form">
        <label className="block text-sm font-medium">Warehouse Code<input data-field={"warehouse_code"} className="input mt-1 cursor-not-allowed bg-slate-100 text-slate-500" readOnly value={warehouseForm.warehouse_code||"Generated automatically after save"}/></label>
        {field("Warehouse Name","name")}
        <label className="block text-sm font-medium">Site Type<select data-field={"site_type"} className="input mt-1" value={warehouseForm.site_type} onChange={e=>setWarehouseForm({...warehouseForm,site_type:e.target.value})}>{["Factory","Construction Site","Distribution Center","Project Site","Office","Other"].map(x=><option key={x}>{x}</option>)}</select></label>
        {field("Facility / Project / Site Name","site_name")}
        <div className="md:col-span-2 rounded-xl border border-blue-200 bg-blue-50 p-3 space-y-3"><div className="font-semibold text-blue-950">Warehouse Operating Calendar</div><label className="block text-sm font-medium">IANA Time Zone<select data-field={"time_zone"} className="input mt-1" required value={warehouseForm.time_zone||""} onChange={e=>setWarehouseForm({...warehouseForm,time_zone:e.target.value})}><option value="">Select time zone...</option>{timeZones.map(zone=><option key={zone}>{zone}</option>)}</select></label><div className="grid gap-2 sm:grid-cols-2"><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={!!warehouseForm.operation_24h_yn} onChange={e=>setWarehouseForm({...warehouseForm,operation_24h_yn:e.target.checked?1:0,operating_start_time:e.target.checked?"00:00":warehouseForm.operating_start_time,operating_end_time:e.target.checked?"00:00":warehouseForm.operating_end_time})}/>24-hour operation</label><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={!!warehouseForm.shifts_enabled_yn} onChange={e=>setWarehouseForm({...warehouseForm,shifts_enabled_yn:e.target.checked?1:0})}/>Enable multiple warehouse shifts</label></div><div className="grid grid-cols-2 gap-3">{field("Operating Start","operating_start_time","time")}{field("Operating End","operating_end_time","time")}</div><div><div className="mb-1 text-xs font-semibold uppercase tracking-wide text-blue-700">Applicable operating days</div><div className="grid grid-cols-2 gap-2 sm:grid-cols-4">{DAY_NAMES.map((name,day)=><label key={name} className="flex items-center gap-2 rounded-lg bg-white px-2 py-1.5 text-xs"><input type="checkbox" checked={(warehouseForm.operating_days||[]).includes(day)} onChange={e=>setWarehouseForm({...warehouseForm,operating_schedule:undefined,operating_days:e.target.checked?[...(warehouseForm.operating_days||[]),day]:(warehouseForm.operating_days||[]).filter(value=>value!==day)})}/>{name}</label>)}</div></div><p className="text-xs text-blue-700">When multiple shifts are disabled, employees follow one standard shift covering these operating hours. Saved multi-shift templates are retained for later reactivation.</p></div>
        <label className="block text-sm font-medium md:col-span-2">Physical Address<textarea data-field={"address"} className="input mt-1" value={warehouseForm.address||""} onChange={e=>setWarehouseForm({...warehouseForm,address:e.target.value})}/></label>
        <label className="block text-sm font-medium">Country<select data-field={"country_code"} className="input mt-1" value={warehouseForm.country_code||""} onChange={e=>setWarehouseForm({...warehouseForm,country_code:e.target.value,city_id:""})}><option value="">Select...</option>{reference.countries.map(c=><option key={c.country_code} value={c.country_code}>{c.country_name}</option>)}</select></label>
        <label className="block text-sm font-medium">City<select data-field={"city_id"} className="input mt-1" value={warehouseForm.city_id||""} onChange={e=>setWarehouseForm({...warehouseForm,city_id:Number(e.target.value)})}><option value="">Select...</option>{reference.cities.filter(c=>c.country_code===warehouseForm.country_code).map(c=><option key={c.id} value={c.id}>{c.city_name}</option>)}</select></label>
        {field("Region / Province","region_province")}{field("Postal Code","postal_code")}
        {error&&<p data-error-message="true" role="alert" className="text-sm text-rose-600 md:col-span-2">{error}</p>}
        <div className="flex justify-end gap-2 md:col-span-2"><button className="btn-secondary" onClick={()=>setShowWh(false)}>Cancel</button><button className="btn-primary" onClick={saveWarehouse}>{warehouseForm.id?"Save Warehouse":"Create Warehouse"}</button></div>
      </div>
    </Modal>}
    {shiftPreview&&<Modal wide title={`Confirm Automatic Shift Design — ${shiftPreview.warehouse_name}`} onClose={()=>setShiftPreview(null)}><div className="space-y-4"><div className="rounded-xl border border-blue-200 bg-blue-50 p-4 text-sm text-blue-950"><strong>Proposed operating window:</strong> {shiftPreview.operating_start_time}–{shiftPreview.operating_end_time}<br/><span>{shiftPreview.shifts_enabled_yn?`${shiftPreview.proposed_shifts.length} shift(s) automatically calculated on standard 30-minute start intervals, with at least two hours between each next start and the previous scheduled end.`:"One standard operating-hours shift will be used because multiple shifts are disabled."}</span></div><div className="overflow-x-auto"><table className="table-base"><thead><tr><th>Shift</th><th>Start</th><th>Scheduled End</th><th>Working Time</th><th>Break</th><th>Scheduled Total</th></tr></thead><tbody>{shiftPreview.proposed_shifts.map(row=><tr key={row.sequence}><td>{row.shift_label||`Shift ${row.sequence}`}</td><td>{row.start_time}</td><td>{row.end_time}</td><td>{(row.working_minutes/60).toFixed(2)} hr</td><td>{row.break_minutes} min</td><td>{(row.scheduled_minutes/60).toFixed(2)} hr</td></tr>)}</tbody></table></div><div className="rounded-lg bg-amber-50 p-3 text-sm text-amber-900">The existing operating times and active schedule remain unchanged until you confirm. Future automatic calendar entries will use the confirmed design.</div>{error&&<p data-error-message="true" role="alert" className="text-sm text-rose-600">{error}</p>}<div className="flex justify-end gap-2"><button className="btn-secondary" onClick={()=>setShiftPreview(null)}>Continue Editing</button><button className="btn-primary" onClick={confirmShiftDesign}>Confirm Operating Times & Shift Design</button></div></div></Modal>}
    {readiness&&<Modal wide title={`Deactivate ${readiness.warehouse.name}`} onClose={()=>setReadiness(null)}><div className="space-y-4"><div className={`rounded-xl border p-4 ${readiness.ready?"border-emerald-200 bg-emerald-50":"border-amber-300 bg-amber-50"}`}><h4 className="font-semibold">{readiness.ready?"Warehouse is ready for controlled deactivation":`${readiness.open_task_count} open task(s) must be resolved`}</h4><p className="mt-1 text-sm">Stock: {readiness.stock_quantity} · FIFO: {readiness.fifo_quantity}. Deactivation creates and permanently retains stock, GRN, issue, return, transfer, adjustment, cycle-count, tool and ledger reports.</p></div>{readiness.open_tasks.map(task=><section key={task.category} className="rounded-xl border border-slate-200 p-3"><h4 className="font-semibold text-rose-700">{task.category} ({task.count})</h4><div className="mt-2 overflow-x-auto"><table className="table-base"><thead><tr>{Object.keys(task.records[0]||{}).map(key=><th key={key}>{key.replaceAll("_"," ")}</th>)}</tr></thead><tbody>{task.records.map((record,index)=><tr key={index}>{Object.keys(task.records[0]||{}).map(key=><td key={key}>{String(record[key]??"—")}</td>)}</tr>)}</tbody></table></div></section>)}{readiness.ready&&<div><label className="block text-sm font-medium">Deactivation Reason<textarea data-field={"deactivationReason"} className="input mt-1" value={deactivationReason} onChange={e=>setDeactivationReason(e.target.value)} placeholder="Explain why this warehouse is being deactivated"/></label><button className="mt-3 rounded-lg bg-rose-700 px-4 py-2 text-sm font-semibold text-white disabled:opacity-50" disabled={deactivationReason.trim().length<5} onClick={deactivateWarehouse}>Confirm Deactivation & Generate Reports</button></div>}{error&&<p data-error-message="true" role="alert" className="text-sm text-rose-600">{error}</p>}</div></Modal>}
    {reportDetail&&<Modal wide title={`Warehouse Deactivation Report ${reportDetail.report_number}`} onClose={()=>setReportDetail(null)}><div className="space-y-4"><div className="grid gap-3 rounded-xl bg-slate-50 p-4 text-sm md:grid-cols-3"><div><strong>Warehouse</strong><br/>{reportDetail.warehouse_code} — {reportDetail.warehouse_name}</div><div><strong>Deactivated</strong><br/>{reportDetail.deactivated_at} by {reportDetail.deactivated_by_name}</div><div><strong>Reason</strong><br/>{reportDetail.deactivation_reason}</div></div>{Object.entries(reportDetail.snapshot?.reports||{}).map(([name,rows])=><section key={name} className="rounded-xl border border-slate-200 p-3"><h4 className="font-semibold capitalize">{name.replaceAll("_"," ")} ({rows.length})</h4>{rows.length>0?<div className="mt-2 max-h-72 overflow-auto"><table className="table-base"><thead><tr>{Object.keys(rows[0]).map(key=><th key={key}>{key.replaceAll("_"," ")}</th>)}</tr></thead><tbody>{rows.map((row,index)=><tr key={index}>{Object.keys(rows[0]).map(key=><td key={key}>{String(row[key]??"—")}</td>)}</tr>)}</tbody></table></div>:<p className="mt-1 text-xs text-slate-500">No records at the time of deactivation.</p>}</section>)}</div></Modal>}
    {showLoc&&<Modal title={locForm.id?`Manage ${locForm.type} ${locForm.code}`:"Create Storage Zone"} onClose={()=>setShowLoc(false)}><div className="space-y-3">
      <label className="block text-sm font-medium">Warehouse Site<select data-field={"warehouse_id"} disabled={!!locForm.id} className="input mt-1" value={locForm.warehouse_id||""} onChange={e=>setLocForm({...locForm,warehouse_id:Number(e.target.value),parent_id:null})}><option value="">Select...</option>{warehouses.map(w=><option key={w.id} value={w.id}>{w.warehouse_code} — {w.name}</option>)}</select></label>
      {locForm.id&&<div className="rounded-lg bg-slate-50 px-3 py-2 text-sm"><strong>Level:</strong> {locForm.type}<br/><strong>Parent:</strong> {locForm.parent_code||"Warehouse"}<br/><strong>Structure:</strong> {structureLabels[locForm.structure_type]||locForm.structure_type}</div>}
      <label className="block text-sm font-medium">Description / Physical Label<input data-field={"label"} className="input mt-1" value={locForm.label||""} onChange={e=>setLocForm({...locForm,label:e.target.value})}/></label>
      {locForm.type==="Zone"&&<div className="grid grid-cols-2 gap-3"><label className="text-sm font-medium">Storage Classification<input data-field={"storage_classification"} className="input mt-1" placeholder="PPE, SAND, REBAR..." value={locForm.storage_classification||"GENERAL"} onChange={e=>setLocForm({...locForm,storage_classification:e.target.value.toUpperCase()})}/></label><label className="text-sm font-medium">Environment<select data-field={"environment"} className="input mt-1" value={locForm.environment||"INDOOR"} onChange={e=>setLocForm({...locForm,environment:e.target.value})}><option>INDOOR</option><option>OUTDOOR</option></select></label><label className="text-sm font-medium">Storage Structure<select data-field={"structure_type"} disabled={!!locForm.id} className="input mt-1" value={locForm.structure_type||"RACK_SHELF_BIN"} onChange={e=>setLocForm({...locForm,structure_type:e.target.value})}>{structures.map(x=><option key={x} value={x}>{structureLabels[x]}</option>)}</select></label>{!locForm.id&&!['OPEN_AREA','QUARANTINE_AREA','REPAIR_AREA'].includes(locForm.structure_type)&&<label className="text-sm font-medium">Number of First-Level Locations<input data-field={"generation_count"} className="input mt-1" type="number" min="0" value={locForm.generation_count||""} onChange={e=>setLocForm({...locForm,generation_count:Number(e.target.value)})}/></label>}</div>}
      {locForm.type!=="Zone"&&<div className="grid grid-cols-2 gap-3"><label className="text-sm font-medium">Capacity Quantity<input data-field={"capacity_quantity"} className="input mt-1" type="number" min="0" value={locForm.capacity_quantity||""} onChange={e=>setLocForm({...locForm,capacity_quantity:Number(e.target.value)})}/></label><label className="text-sm font-medium">Capacity UOM<input data-field={"capacity_uom"} className="input mt-1" value={locForm.capacity_uom||""} onChange={e=>setLocForm({...locForm,capacity_uom:e.target.value.toUpperCase()})}/></label><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={!!locForm.secure_storage} onChange={e=>setLocForm({...locForm,secure_storage:e.target.checked?1:0})}/>Secure storage</label><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={!!locForm.temperature_controlled} onChange={e=>setLocForm({...locForm,temperature_controlled:e.target.checked?1:0})}/>Temperature controlled</label></div>}
      {locForm.type==="Bin"&&<div className="grid grid-cols-2 gap-3"><label className="text-sm font-medium">BIN Type<select data-field={"location_type"} className="input mt-1" value={locForm.location_type||"Standard BIN"} onChange={e=>setLocForm({...locForm,location_type:e.target.value})}>{["Standard BIN","Pallet Location","Bulk Storage","Tool Storage","Quarantine","Inspection","Rejected Material","Damaged Material","Return Area","Receiving Area","Staging Area","Outdoor Yard","Chemical Storage","Floor Storage","Bay","Tank","Silo"].map(x=><option key={x}>{x}</option>)}</select></label><label className="text-sm font-medium">Status<select data-field={"status"} className="input mt-1" value={locForm.status||"Available"} onChange={e=>setLocForm({...locForm,status:e.target.value})}>{["Available","Partially Available","Full","Blocked","Under Inspection","Maintenance","Quarantine","Inactive"].map(x=><option key={x}>{x}</option>)}</select></label></div>}
      {locForm.id&&locForm.type==="Rack"&&["RACK_SHELF_BIN","AISLE_RACK_SHELF_BIN"].includes(locForm.structure_type)&&<label className="text-sm font-medium">Desired Total Shelves<input data-field={"generation_count"} className="input mt-1" type="number" min="1" value={locForm.generation_count||""} onChange={e=>setLocForm({...locForm,generation_count:Number(e.target.value)})}/></label>}
      {locForm.id&&locForm.type==="Shelf"&&<label className="text-sm font-medium">Bins to Generate<input data-field={"generation_count"} className="input mt-1" type="number" min="1" value={locForm.generation_count||""} onChange={e=>setLocForm({...locForm,generation_count:Number(e.target.value)})}/></label>}
      {locForm.id&&!locForm.is_terminal_storage&&locForm.type!=="Rack"&&locForm.type!=="Shelf"&&locForm.type!=="Zone"&&<label className="text-sm font-medium">Desired Total Next-Level Locations<input data-field={"generation_count"} className="input mt-1" type="number" min="1" value={locForm.generation_count||""} onChange={e=>setLocForm({...locForm,generation_count:Number(e.target.value)})}/></label>}
      {locForm.id&&locForm.type==="Zone"&&!locForm.is_terminal_storage&&<label className="text-sm font-medium">Desired Total First-Level Locations<input data-field={"generation_count"} className="input mt-1" type="number" min="1" value={locForm.generation_count||""} onChange={e=>setLocForm({...locForm,generation_count:Number(e.target.value)})}/></label>}
      {locForm.id&&locForm.type==="Zone"&&["AISLE_RACK_SHELF_BIN","RACK_SHELF_BIN"].includes(locForm.structure_type)&&<details className="rounded-lg border border-blue-200 p-3"><summary className="cursor-pointer font-medium text-blue-800">Quick Setup</summary><div className="mt-3 grid grid-cols-2 gap-2">{(locForm.structure_type==="AISLE_RACK_SHELF_BIN"?[["aisles","Aisles"],["racks_per_aisle","Racks per Aisle"]]:[["racks","Racks"]]).concat([["shelves_per_rack","Shelves per Rack"],["bins_per_shelf","Bins per Shelf"]]).map(([key,label])=><label key={key} className="text-xs font-medium">{label}<input className="input mt-1" type="number" min="1" value={locForm.quick?.[key]||""} onChange={e=>setLocForm({...locForm,quick:{...(locForm.quick||{}),[key]:Number(e.target.value)}})}/></label>)}</div><button className="btn-secondary mt-3" onClick={quickSetup}>Generate Standard Layout</button></details>}
      {error&&<p data-error-message="true" role="alert" className="text-sm text-rose-600">{error}</p>}<div className="flex justify-between gap-2">{locForm.id&&canDeactivate?<button className="rounded-lg border border-rose-300 px-3 py-2 text-sm font-semibold text-rose-700 hover:bg-rose-50" onClick={deleteLocation}>Delete Empty {locForm.type}</button>:<span/>}<div className="flex gap-2"><button className="btn-secondary" onClick={()=>setShowLoc(false)}>Cancel</button><button className="btn-primary" onClick={saveLocation}>{locForm.id?"Save & Generate Children":locForm.generation_count?`Create Zone & Generate ${locForm.structure_type==="BAY"?"Bays":locForm.structure_type==="YARD_SLOT"?"Yard Slots":locForm.structure_type==="GROUND_STACK"?"Ground Stacks":"Racks"}`:"Create Zone"}</button></div></div>
    </div></Modal>}
  </div>;
}
