import { BRAND_LOGO_DATA } from './brandAsset';
import { PRODUCT_BRAND } from './brand';

export const DOCUMENT_THEME = Object.freeze({
  product: PRODUCT_BRAND.name,
  tagline: PRODUCT_BRAND.tagline,
  generatedBy: `Generated by ${PRODUCT_BRAND.name}`,
  logo: BRAND_LOGO_DATA,
  colors: Object.freeze({
    navy: '#052f5f',
    blue: '#075fa8',
    teal: '#0796a5',
    green: '#16843a',
    white: '#ffffff',
    background: '#f2f7fa',
    border: '#c8dbe5',
    text: '#202b33',
    muted: '#526671',
  }),
});

export function drawPdfBrandFooter(pdf, { pageWidth, margin, footerTop, pageLabel }) {
  pdf.setDrawColor(180, 190, 200);
  pdf.setLineWidth(.2);
  pdf.line(margin, footerTop + 1, pageWidth - margin, footerTop + 1);
  pdf.saveGraphicsState();
  pdf.roundedRect(margin, footerTop + 3, 30, 10, 1.5, 1.5, null);
  pdf.clip();
  pdf.discardPath();
  pdf.addImage(BRAND_LOGO_DATA, 'PNG', margin, footerTop + 3, 30, 10);
  pdf.restoreGraphicsState();
  pdf.setFont('helvetica', 'normal');
  pdf.setFontSize(6.5);
  pdf.setTextColor(82, 102, 113);
  pdf.text(DOCUMENT_THEME.tagline, margin, footerTop + 16);
  pdf.setFontSize(8);
  pdf.text(pageLabel, pageWidth - margin, footerTop + 8, { align: 'right' });
  pdf.setFontSize(6.5);
  pdf.text('CONTROLLED DOCUMENT', pageWidth - margin, footerTop + 12, { align: 'right' });
  pdf.setTextColor(0, 0, 0);
}
