import { CompanyContact, CompanyLogo, GeneratedByFooter } from './Branding';
import { ResponsibleSignature } from './EmployeeSignature';

const money = value => Number(value || 0).toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 });

export default function EmployeeClearanceDocument({ document }) {
  const snap = document.snapshot || {}, company = snap.company || {}, employee = snap.employee || {}, verification = snap.verification || {};
  const clear = document.document_type === 'Clearance Certificate';
  const generated = snap.generated_by || {};
  return <article id="employee-clearance-print-document" data-output-authorized="true" className="controlled-print-document rounded-lg border border-slate-200 bg-white p-7 text-slate-900">
    <header className="flex justify-between gap-6 border-b-2 border-blue-800 pb-5">
      <div className="flex min-w-0 gap-4"><CompanyLogo company={company} size="document"/><div><h1 className="text-xl font-bold text-blue-950">{company.name || company.company_name || 'Company Name'}</h1><div className="mt-1 whitespace-pre-line text-xs leading-5 text-slate-600">{company.address}</div><CompanyContact company={company}/></div></div>
      <div className="text-right"><div className="text-xl font-bold tracking-wide text-blue-950">{clear ? 'EMPLOYEE CLEARANCE CERTIFICATE' : 'EMPLOYEE CLEARANCE STATUS'}</div><div className="mt-2 text-sm font-bold">{document.document_number}</div><div className="text-xs text-slate-600">Issued: {new Date(document.generated_at || Date.now()).toLocaleString()}</div></div>
    </header>
    <section className="my-6 text-sm leading-7"><h2 className="mb-3 font-bold">TO WHOM IT MAY CONCERN</h2>
      <p>{clear ? `This is to certify that ${employee.employee_name}, Employee ID ${employee.employee_code}, holding the position of ${employee.position || '—'} in the ${employee.department || '—'}, has completed the required employee clearance process for ${company.name || company.company_name || 'the Company'}. Based on the records available in Procuraflo, including applicable records from all warehouse locations operated under the company, there are no outstanding returnable materials, tools, equipment, assets, or other company property recorded against this employee, and there are no unresolved company-property liabilities pending review.` : `This is to confirm that ${employee.employee_name}, Employee ID ${employee.employee_code}, has been reviewed as part of the HR Clearance Process. The returnable company property or liabilities below remain outstanding across the Company's applicable warehouse locations.`}</p>
    </section>
    <section className={`mb-5 rounded-lg border-2 p-4 text-center ${clear ? 'border-emerald-300 bg-emerald-50 text-emerald-800' : 'border-amber-300 bg-amber-50 text-amber-900'}`}><div className="text-lg font-extrabold">{clear ? '✓ CLEAR FOR HR PROCESSING' : '⚠ NOT CLEAR – OUTSTANDING COMPANY PROPERTY / LIABILITY'}</div></section>
    {!clear && <table className="w-full border-collapse text-[10px]"><thead><tr className="bg-blue-900 text-white">{['Warehouse','Item','Description','Serial / Asset No.','Qty Outstanding','Condition','Liability Status','Unit Value','Outstanding Value'].map(x=><th className="border border-blue-800 p-2 text-left" key={x}>{x}</th>)}</tr></thead><tbody>{[...(verification.items || []), ...(verification.unresolved_liabilities || []).map(x=>({...x,outstanding_qty:0,unit_value:x.liability_value,outstanding_value:x.liability_value,return_condition:x.condition}))].map((x,i)=><tr key={`${x.source_type}-${x.id || x.issue_line_id || i}`}><td className="border p-2">{x.warehouse_name}</td><td className="border p-2">{x.item_code}</td><td className="border p-2">{x.description}</td><td className="border p-2">{x.serial_asset_no || '—'}</td><td className="border p-2 text-right">{x.outstanding_qty}</td><td className="border p-2">{x.return_condition || x.condition || '—'}</td><td className="border p-2">{x.liability_status}</td><td className="border p-2 text-right">{snap.currency} {money(x.unit_value)}</td><td className="border p-2 text-right">{snap.currency} {money(x.outstanding_value)}</td></tr>)}</tbody></table>}
    <section className="mt-5 grid grid-cols-3 gap-3 text-xs"><div className="rounded border p-3">Outstanding Returnable Items<strong className="block text-lg">{verification.outstanding_item_count || 0}</strong></div><div className="rounded border p-3">Unresolved Liabilities<strong className="block text-lg">{verification.unresolved_liability_count || 0}</strong></div><div className="rounded border p-3">Outstanding Value<strong className="block text-lg">{snap.currency} {money(verification.outstanding_value)}</strong></div></section>
    <section className="mt-14 grid grid-cols-2 gap-16 text-center text-xs"><ResponsibleSignature label="Supply Chain Manager" name={generated.full_name} src={generated.signature_url} date={document.generated_at}/><div className="border-t border-slate-500 pt-2">Human Resources Acknowledgement</div></section>
    <GeneratedByFooter note="This company-property accountability document supports the Company's Human Resources clearance, employee release, and final settlement process. Procuraflo does not execute payroll deductions or settlement decisions."/>
  </article>;
}
