import {CompanyContact,CompanyLogo,GeneratedByFooter} from './Branding';
import {ResponsibleSignature} from './EmployeeSignature';
import {formatCurrency} from '../utils/currency';
const date=value=>value?new Date(value).toLocaleDateString():'Not recorded';
export default function ProfessionalMaterialIssue({issue}){
 const company=issue.company||{};
 const fields=[['Employee',`${issue.employee_code||''} ${issue.employee_name||''}`],['Department',issue.employee_department_name],['Purpose',issue.purpose]];
 return <article id="material-issue-print-document" className="controlled-print-document rounded-lg border border-slate-200 bg-white p-7 text-slate-900">
  <header className="flex justify-between gap-6 border-b-2 border-blue-800 pb-5">
   <div className="flex min-w-0 gap-4"><CompanyLogo company={company} size="document"/><div><h1 className="text-xl font-bold text-blue-950">{company.name||'Company Name'}</h1><div className="mt-1 whitespace-pre-line text-xs leading-5 text-slate-600">{company.address||'Company address not configured'}</div><CompanyContact company={company}/></div></div>
   <div className="shrink-0 text-right"><div className="text-2xl font-bold tracking-wide text-blue-950">MATERIAL ISSUE</div><div className="mt-2 text-sm font-bold">{issue.issue_number}</div><div className="text-xs text-slate-600">Issue Date: {date(issue.issue_date||issue.created_at)}</div><div className="text-xs text-slate-600">Fiscal Year: {company.financial_year||'Not configured'}</div></div>
  </header>
  <section className="my-5 grid grid-cols-2 gap-5 text-xs">
   <div className="overflow-hidden rounded-md border border-slate-300"><div className="bg-blue-50 px-3 py-2 font-bold uppercase tracking-wide text-blue-950">Recipient & Purpose</div><dl className="space-y-2 p-3">{fields.map(([label,value])=><div key={label}><dt className="text-slate-500">{label}</dt><dd className="font-semibold whitespace-pre-line">{value||'Not specified'}</dd></div>)}</dl></div>
   <div className="overflow-hidden rounded-md border border-slate-300"><div className="bg-blue-50 px-3 py-2 font-bold uppercase tracking-wide text-blue-950">Document Control</div><div className="space-y-2 p-3"><div>Status: <strong>{issue.status}</strong></div><div>Prepared By: <strong>{issue.prepared_by_name||'Not recorded'}</strong></div><div>Approved By: <strong>{issue.approved_by_name||'Pending approval'}</strong></div>{issue.status==='PendingApproval'&&<p className="text-amber-700">Pending approval. This document does not authorize stock release.</p>}</div></div>
  </section>
  <table className="w-full border-collapse text-[10px]"><thead><tr className="bg-blue-900 text-white">{['#','Item Code & Description','Warehouse / Location','Quantity / UOM','Unit Cost','Value'].map(label=><th key={label} className="border border-blue-800 p-2 text-left">{label}</th>)}</tr></thead><tbody>{(issue.items||[]).map((line,index)=><tr key={line.id||index} className={index%2?'bg-slate-50':'bg-white'}><td className="border border-slate-300 p-2">{index+1}</td><td className="border border-slate-300 p-2"><strong>{line.item_code}</strong><div>{line.description}</div></td><td className="border border-slate-300 p-2">{line.warehouse_name}<div>{line.site_name}</div><div>{line.location_code||'Legacy / unassigned'}</div></td><td className="border border-slate-300 p-2 text-right">{Number(line.quantity||0).toLocaleString()} {line.transaction_uom||line.uom||line.base_uom}</td><td className="border border-slate-300 p-2 text-right">{formatCurrency(Number(line.quantity)?Number(line.value||0)/Number(line.quantity):0)}</td><td className="border border-slate-300 p-2 text-right">{formatCurrency(line.value)}</td></tr>)}</tbody></table>
  <section className="mt-4 flex justify-end text-sm print-avoid-break"><div className="w-80 rounded border border-blue-200 bg-blue-50 p-3 text-right font-bold">{issue.status==='PendingApproval'?'Estimated Issue Value':'Total Issue Value'}: {formatCurrency(issue.total_value)}</div></section>
  <section className="mt-14 grid grid-cols-3 gap-8 text-center text-xs print-avoid-break"><ResponsibleSignature label="Prepared by" name={issue.prepared_by_name} src={issue.prepared_by_signature_url} date={issue.created_at||issue.issue_date} lookupByName={false} missingDateLabel="Preparation date not recorded"/><ResponsibleSignature label="Approved by" name={issue.approved_by_name} src={issue.approved_by_signature_url} date={issue.approved_at} lookupByName={false} missingDateLabel={issue.status==="PendingApproval"?"Pending approval":"Approval date not recorded"}/><ResponsibleSignature label="Received by" name={issue.employee_name} src={issue.received_by_signature_url} lookupByName={false} missingDateLabel="Receipt signature / date"/></section>
  <GeneratedByFooter note="Company material issue record. Physical handover must follow the recorded approval and warehouse stock-release controls."/>
 </article>;
}
