import { useEffect, useMemo, useState } from 'react';
import { printElement } from '../utils/printCopies';
import client from '../api/client';
import DataTable from '../components/DataTable';
import Modal from '../components/Modal';
import SearchSelect from '../components/SearchSelect';
import StatusBadge from '../components/StatusBadge';
import EmployeeClearanceDocument from '../components/EmployeeClearanceDocument';
import { downloadElementPdf } from '../utils/downloadPdf';
import { useBranding } from '../contexts/BrandingContext';
import { useAuth } from '../contexts/AuthContext';
import { brandedSpreadsheetHtml } from '../utils/brandedSpreadsheet';
import useAutoRefresh from '../hooks/useAutoRefresh';

const reasons = ['Resignation','Termination','Contract Completion','Retirement','Transfer / Permanent Release','End of Project Assignment','Other'];
const money = (v,c='SAR') => `${c} ${Number(v || 0).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})}`;

export default function EmployeeClearancePage() {
  const [rows,setRows]=useState([]),[employees,setEmployees]=useState([]),[detail,setDetail]=useState(null),[form,setForm]=useState({clearance_reason:'Resignation'}),[showStart,setShowStart]=useState(false),[liability,setLiability]=useState(null),[document,setDocument]=useState(null),[report,setReport]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState('');
  const { company }=useBranding(),{ user }=useAuth();
  const load=async()=>{setLoading(true);try{const [r,e]=await Promise.all([client.get('/employee-clearance'),client.get('/employee-clearance/employees')]);setRows(r.data);setEmployees(e.data);}catch(e){setError(e?.response?.data?.error||'Unable to load Employee Clearance');}finally{setLoading(false);}};
  useAutoRefresh(load);
  useEffect(()=>{load();},[]);
  const open=async id=>{try{setDetail((await client.get(`/employee-clearance/${id}`)).data);setError('');}catch(e){setError(e?.response?.data?.error||'Unable to open clearance');}};
  const start=async()=>{try{const {data}=await client.post('/employee-clearance',form);setShowStart(false);setForm({clearance_reason:'Resignation'});await load();await open(data.id);}catch(e){setError(e?.response?.data?.error||'Unable to start clearance');}};
  const resolve=async()=>{try{await client.post(`/employee-clearance/${detail.id}/liabilities/${liability.id}/resolve`,liability);setLiability(null);await open(detail.id);await load();}catch(e){setError(e?.response?.data?.error||'Unable to resolve liability');}};
  const cancel=async()=>{const reason=window.prompt('Cancellation reason (required)');if(!reason)return;try{await client.post(`/employee-clearance/${detail.id}/cancel`,{cancellation_reason:reason});await open(detail.id);await load();}catch(e){setError(e?.response?.data?.error||'Unable to cancel clearance');}};
  const generate=async type=>{try{const {data}=await client.post(`/employee-clearance/${detail.id}/documents`,{document_type:type});setDocument(data);await open(detail.id);await load();}catch(e){setError(e?.response?.data?.error||'Document generation failed');}};
  const viewDocument=async id=>{try{setDocument((await client.get(`/employee-clearance/documents/${id}`)).data);}catch(e){setError(e?.response?.data?.error||'Unable to retrieve document');}};
  const print=()=>printElement('employee-clearance-print-document');
  const download=async()=>{const e=document?.snapshot?.employee||{},safe=`Employee_Clearance_${e.employee_code||'Employee'}_${e.employee_name||''}_${document.document_number}`.replace(/[^a-z0-9_-]+/gi,'_');await downloadElementPdf('employee-clearance-print-document',`${safe}.pdf`);};
  const audit=async()=>setReport((await client.get('/employee-clearance/audit-report')).data);
  const exportExcel=()=>{const table=window.document.getElementById('clearance-audit-table')?.outerHTML||'';const html=brandedSpreadsheetHtml({companyName:company.company_name,title:'Employee Clearance Audit Report',generatedBy:user.full_name,tableHtml:table});const a=window.document.createElement('a');a.href=URL.createObjectURL(new Blob([html],{type:'application/vnd.ms-excel'}));a.download='Employee_Clearance_Audit.xls';a.click();URL.revokeObjectURL(a.href);};
  const employeeOptions=useMemo(()=>employees.map(e=>({value:e.id,label:`${e.employee_code} — ${e.name} · ${e.department||'No department'}`})),[employees]);
  return <div>
    <div className="mb-4 flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-xl font-semibold text-slate-900">Employee Clearance Register</h1><p className="text-sm text-slate-500">Company-wide returnable-property accountability for the HR Clearance Process.</p></div><div className="flex gap-2"><button className="btn-secondary" onClick={audit}>Audit Report</button><button className="btn-primary" onClick={()=>setShowStart(true)}>+ Start Clearance</button></div></div>
    {error&&<div data-error-message="true" role="alert" className="mb-3 rounded-lg bg-rose-50 px-3 py-2 text-sm text-rose-700">{error}</div>}
    <div className="card"><DataTable loading={loading} rows={rows} onRowDoubleClick={r=>open(r.id)} columns={[{key:'clearance_number',label:'Clearance No.'},{key:'employee_code',label:'Employee ID'},{key:'employee_name',label:'Employee Name'},{key:'department',label:'Department'},{key:'request_date',label:'Request Date'},{key:'clearance_reason',label:'Reason'},{key:'current_outstanding_item_count',label:'Outstanding Items'},{key:'unresolved_liability_count',label:'Liabilities'},{key:'current_outstanding_value',label:'Outstanding Value',render:r=>money(r.current_outstanding_value)},{key:'current_status',label:'Status',render:r=><StatusBadge status={r.current_status}/>},{key:'clearance_age',label:'Age (days)'},{key:'letter_status',label:'Letter Status'}]}/></div>
    {showStart&&<Modal title="Start Employee Clearance" onClose={()=>setShowStart(false)}><div className="compact-form"><SearchSelect label="Employee" options={employeeOptions} value={form.employee_id||''} onChange={v=>setForm({...form,employee_id:Number(v)})} placeholder="Search Employee Master"/><label className="text-sm font-medium">Clearance Reason<select className="input mt-1" value={form.clearance_reason} onChange={e=>setForm({...form,clearance_reason:e.target.value})}>{reasons.map(x=><option key={x}>{x}</option>)}</select></label>{form.clearance_reason==='Other'&&<label className="text-sm font-medium">Comments<textarea className="input mt-1" value={form.reason_comments||''} onChange={e=>setForm({...form,reason_comments:e.target.value})}/></label>}<div className="flex justify-end gap-2"><button className="btn-secondary" onClick={()=>setShowStart(false)}>Cancel</button><button className="btn-primary" onClick={start}>Run Company-wide Scan</button></div></div></Modal>}
    {detail&&<Modal wide title={`${detail.clearance_number} — ${detail.employee_name}`} onClose={()=>setDetail(null)}><div className="space-y-5">
      <div className={`rounded-xl border-2 p-4 ${detail.status==='Clear for HR Processing'?'border-emerald-300 bg-emerald-50':'border-amber-300 bg-amber-50'}`}><div className="flex flex-wrap items-center justify-between gap-2"><div className="text-lg font-bold">{detail.status==='Clear for HR Processing'?'✓ CLEAR FOR HR PROCESSING':detail.status==='Cancelled'?'CANCELLED':'⚠ '+detail.status.toUpperCase()}</div><div className="flex flex-wrap gap-2">{detail.status==='Clear for HR Processing'?<button className="btn-primary" onClick={()=>generate('Clearance Certificate')}>Generate Clearance Letter</button>:detail.status!=='Cancelled'&&<button className="btn-primary" onClick={()=>generate('Clearance Status')}>Generate Status Letter</button>}{detail.status!=='Cancelled'&&<button className="btn-secondary" onClick={cancel}>Cancel Clearance</button>}</div></div></div>
      <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{[['Outstanding Items',detail.outstanding_item_count],['Unresolved Liabilities',detail.unresolved_liability_count],['Outstanding Value',money(detail.outstanding_value,detail.currency)],['Warehouses Checked',detail.warehouses_checked_count],['Clearance Age',`${detail.clearance_age} days`]].map(([k,v])=><div key={k} className="rounded-lg border bg-slate-50 p-3 text-xs text-slate-500">{k}<strong className="mt-1 block text-base text-slate-900">{v}</strong></div>)}</div>
      <section><h2 className="mb-2 font-semibold">Company-wide Warehouse Summary</h2><DataTable searchable={false} rows={detail.warehouse_summary} columns={[{key:'warehouse_name',label:'Warehouse'},{key:'outstanding_item_lines',label:'Item Lines'},{key:'outstanding_qty',label:'Outstanding Qty'},{key:'unresolved_liabilities',label:'Liabilities'},{key:'outstanding_value',label:'Value',render:r=>money(r.outstanding_value,detail.currency)}]}/></section>
      <section><h2 className="mb-2 font-semibold">Outstanding Property Details</h2><DataTable searchable={false} rows={detail.items} columns={[{key:'warehouse_name',label:'Warehouse'},{key:'item_code',label:'Item Code'},{key:'description',label:'Description'},{key:'serial_asset_no',label:'Serial / Asset No.'},{key:'issue_number',label:'Issue Ref.'},{key:'issue_date',label:'Issue Date'},{key:'qty_issued',label:'Issued'},{key:'qty_returned',label:'Returned'},{key:'outstanding_qty',label:'Outstanding'},{key:'liability_status',label:'Liability Status'},{key:'outstanding_value',label:'Value',render:r=>money(r.outstanding_value,detail.currency)}]}/></section>
      <section><h2 className="mb-2 font-semibold">Property Liabilities</h2><DataTable searchable={false} rows={detail.liabilities} onRowDoubleClick={r=>setLiability({...r,resolution_status:'Resolved'})} columns={[{key:'warehouse_name',label:'Warehouse'},{key:'item_code',label:'Item'},{key:'description',label:'Description'},{key:'condition',label:'Condition'},{key:'liability_status',label:'Status'},{key:'liability_value',label:'Value',render:r=>money(r.liability_value,detail.currency)},{key:'resolution_reason',label:'Resolution'}]}/></section>
      <section><h2 className="mb-2 font-semibold">Document History</h2><DataTable searchable={false} rows={detail.documents} onRowDoubleClick={r=>viewDocument(r.id)} columns={[{key:'document_number',label:'Document No.'},{key:'document_type',label:'Type'},{key:'status_snapshot',label:'Status at Issue'},{key:'total_outstanding_value_snapshot',label:'Value at Issue',render:r=>money(r.total_outstanding_value_snapshot,detail.currency)},{key:'generated_at',label:'Generated'},{key:'generated_by_name',label:'Generated By'}]}/></section>
      <section><h2 className="mb-2 font-semibold">Audit Trail</h2><DataTable searchable={false} rows={detail.audit_history} columns={[{key:'changed_at',label:'Date / Time'},{key:'action',label:'Event'},{key:'performed_by_name',label:'Performed By'},{key:'old_values',label:'Previous'},{key:'new_values',label:'New / Reason'}]}/></section>
    </div></Modal>}
    {liability&&<Modal title="Resolve Company-property Liability" onClose={()=>setLiability(null)}><div className="compact-form"><div className="rounded bg-slate-50 p-3 text-sm"><strong>{liability.item_code} — {liability.description}</strong><div>{liability.warehouse_name} · {liability.condition} · {money(liability.liability_value,detail.currency)}</div></div><label className="text-sm font-medium">Resolution Status<select className="input mt-1" value={liability.resolution_status} onChange={e=>setLiability({...liability,resolution_status:e.target.value})}><option>Resolved</option><option>Liability Waived</option><option>Recovery / Charge Approved</option></select></label><label className="text-sm font-medium">Mandatory Resolution Reason<textarea className="input mt-1" value={liability.resolution_reason||''} onChange={e=>setLiability({...liability,resolution_reason:e.target.value})}/></label><label className="text-sm font-medium">Approval / Reference Number (optional)<input className="input mt-1" value={liability.resolution_reference||''} onChange={e=>setLiability({...liability,resolution_reference:e.target.value})}/></label><button className="btn-primary" onClick={resolve}>Resolve Specific Liability</button></div></Modal>}
    {document&&<Modal wide title={`${document.document_number} — ${document.document_type}`} onClose={()=>setDocument(null)}><div className="mb-3 flex justify-end gap-2 print:hidden"><button className="btn-secondary" onClick={print}>Print</button><button className="btn-primary" onClick={download}>Download PDF</button></div><EmployeeClearanceDocument document={document}/></Modal>}
    {report&&<Modal wide title="Employee Clearance Audit Report" onClose={()=>setReport(null)}><div className="space-y-4"><div className="flex justify-end gap-2 print:hidden"><button className="btn-secondary" onClick={print}>Print</button><button className="btn-primary" onClick={exportExcel}>Export Excel</button></div><div className="grid grid-cols-2 gap-3 md:grid-cols-4">{Object.entries(report.summary).map(([k,v])=><div className="rounded border bg-slate-50 p-3 text-xs" key={k}>{k.replaceAll('_',' ')}<strong className="block text-lg">{v}</strong></div>)}</div><div className="max-w-full overflow-x-auto"><table id="clearance-audit-table" className="table-base"><thead><tr>{['Clearance No.','Employee ID','Employee','Department','Reason','Request Date','Warehouses Checked','Initial Items','Initial Value','Current Value','Initial Status','Current Status','Age','Final Verification','Clearance Date','Letter Status','Cancellation'].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{report.rows.map(r=><tr key={r.id}><td>{r.clearance_number}</td><td>{r.employee_code}</td><td>{r.employee_name}</td><td>{r.department}</td><td>{r.clearance_reason}</td><td>{r.request_date}</td><td>{r.warehouses_checked_count}</td><td>{r.initial_outstanding_item_count}</td><td>{r.initial_outstanding_value}</td><td>{r.current_outstanding_value}</td><td>{r.initial_status}</td><td>{r.current_status}</td><td>{r.clearance_age}</td><td>{r.final_verification_at}</td><td>{r.clearance_date}</td><td>{r.letter_status}</td><td>{r.cancellation_reason}</td></tr>)}</tbody></table></div></div></Modal>}
  </div>;
}
