import {useEffect,useState} from "react";
import client from "../api/client";

const DAYS=["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"];
export default function ProcurementSchedulePage({onSaved, embedded=false}){
  const [form,setForm]=useState({shifts_enabled_yn:0,operating_start_time:"08:00",operating_end_time:"17:00",operating_days:[0,1,2,3,4]}),[message,setMessage]=useState(""),[saving,setSaving]=useState(false);
  useEffect(()=>{client.get("/workforce/reference").then(r=>{if(r.data.shift_mode?.procurement)setForm(r.data.shift_mode.procurement)}).catch(e=>setMessage(e.response?.data?.error||"Unable to load procurement schedule"))},[]);
  async function save(){if(saving)return;setSaving(true);setMessage("");try{const r=await client.put("/workforce/shift-mode/procurement",form);setForm(r.data.procurement);setMessage("Procurement operating schedule saved.");await onSaved?.()}catch(e){setMessage(e.response?.data?.error||"Unable to update procurement schedule")}finally{setSaving(false)}}
  return <div><div className="mb-4"><h2 className="text-xl font-semibold">{embedded ? "Procurement Shift Setup" : "Procurement Operating Schedule"}</h2><p className="text-sm text-slate-500">Configure procurement operating hours and whether the team uses rotating shifts.</p></div><section className="card p-5"><fieldset disabled={saving}><div className="grid gap-3 md:grid-cols-4"><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={!!form.shifts_enabled_yn} onChange={e=>setForm({...form,shifts_enabled_yn:e.target.checked?1:0})}/>Enable procurement shifts</label><label className="text-sm font-medium">Operating Start<input data-field={"operating_start_time"} className="input mt-1" type="time" value={form.operating_start_time} onChange={e=>setForm({...form,operating_start_time:e.target.value})}/></label><label className="text-sm font-medium">Operating End<input data-field={"operating_end_time"} className="input mt-1" type="time" value={form.operating_end_time} onChange={e=>setForm({...form,operating_end_time:e.target.value})}/></label><div className="flex items-end"><button className="btn-primary w-full" onClick={save}>{saving ? "Saving..." : "Save Procurement Schedule"}</button></div></div><div className="mt-4 flex flex-wrap gap-2">{DAYS.map((name,day)=><label key={name} className="flex items-center gap-2 rounded-lg bg-slate-50 px-3 py-2 text-xs"><input type="checkbox" checked={(form.operating_days||[]).includes(day)} onChange={e=>setForm({...form,operating_days:e.target.checked?[...(form.operating_days||[]),day]:(form.operating_days||[]).filter(x=>x!==day)})}/>{name}</label>)}</div></fieldset>{message&&<p className="mt-3 text-sm text-blue-700">{message}</p>}</section></div>
}
