import { BRAND_LOGO_DATA } from '../config/brandAsset';
import { DOCUMENT_THEME } from '../config/documentTheme';

const escape = value => String(value ?? '')
  .replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;').replaceAll('"', '&quot;');

export function brandedSpreadsheetHtml({ companyName, title, generatedBy, generatedAt, filters, tableHtml }) {
  const c = DOCUMENT_THEME.colors;
  return `<!doctype html><html><head><meta charset="utf-8"><style>
    @page{size:A4 landscape;margin:10mm}
    body{font-family:Arial,sans-serif;color:${c.text}}
    .identity{color:${c.navy};font-size:20px;font-weight:700}
    .title{color:${c.blue};font-size:16px;font-weight:700}
    .meta{color:${c.muted};font-size:10px}
    table{border-collapse:collapse}th{color:#fff;background:${c.navy};font-weight:700}
    th,td{border:1px solid ${c.border};padding:6px 8px}tr:nth-child(even) td{background:${c.background}}
  </style></head><body>
    <div style="background:#202543;padding:8px;border-radius:12px;overflow:hidden;width:180px"><img src="${BRAND_LOGO_DATA}" alt="${escape(DOCUMENT_THEME.product)}" width="180" style="border-radius:10px" /></div>
    <div class="identity">${escape(companyName || 'Company Name')}</div>
    <div class="title">${escape(title)}</div>
    <div class="meta">Generated by ${escape(generatedBy || DOCUMENT_THEME.product)} · ${escape(generatedAt || new Date().toLocaleString())}</div>
    <div class="meta">Filters: ${escape(filters || 'All available records')}</div>
    ${tableHtml}
  </body></html>`;
}
