import { installErrorGuidance } from './utils/errorGuidance';
import { jsx as _jsx } from "react/jsx-runtime";
import ReactDOM from 'react-dom/client';
import { BrowserRouter } from 'react-router-dom';
import App from './App';
import { AuthProvider } from './contexts/AuthContext';
import { BrandingProvider } from './contexts/BrandingContext';
import PageErrorBoundary from './components/PageErrorBoundary';
import './index.css';
installErrorGuidance();
ReactDOM.createRoot(document.getElementById('root')).render(_jsx(PageErrorBoundary, { children: _jsx(BrowserRouter, { children: _jsx(BrandingProvider, { children: _jsx(AuthProvider, { children: _jsx(App, {}) }) }) }) }));
